from customtkinter import *
Font_Under=("Times New Roman (Headings CS)",25)
Mainroot=CTk()
AddTaskWindow=CTkToplevel(Mainroot)
AddTaskWindow.title("Add Task")
AddTaskWindow.geometry("350x180")
Task_Name=CTkLabel(AddTaskWindow,text="Task Name",font=Font_Under)
Task_Name.place(x=90,y=10)
Task_Name_Ent=CTkEntry(AddTaskWindow,width=200,height=20,border_width=0)
Task_Name_Ent.place(x=70,y=40)
Task_Role=CTkLabel(AddTaskWindow,text="Task Badge",font=Font_Under)
Task_Role.place(x=90,y=70)
Task_Role=CTkLabel(AddTaskWindow,text=None,width=60,height=70,font=Font_Under,bg_color="#30eb23",corner_radius=0.5)
Task_Role.place(x=90,y=100)
# Task_Role=CTkLabel(AddTaskWindow,text="Task Badge",font=Font_Under)
# Task_Role.place(x=90,y=70)
# Task_Role=CTkLabel(AddTaskWindow,text="Task Badge",font=Font_Under)
# Task_Role.place(x=90,y=70)
Mainroot.mainloop()